on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly

name: quarto-publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev imagemagick

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::pacman
            any::remotes
            any::rmarkdown
            any::knitr
            any::downlit
            any::xml2
            any::ape
            any::Biostrings
            any::BiocManager
            any::igraph
            any::phylobase
            any::emojifont
            any::ggplot2
            any::dplyr
            any::kableExtra
            any::cowplot
            any::patchwork
            any::aplot
            any::phytools
            any::hexbin
            any::TDbook
            any::ggimage
            any::phyloseq
            any::treemap
            any::ggstar
            any::MicrobiotaProcess
            any::muscle
            any::pwalign
            any::tanggle
            any::gggenes
            any::ggforce
            any::ggtext
            any::ggbreak
            any::rotl
            any::gridSVG
            any::data.tree
            any::rsvg
            any::tidyverse
            any::jsonlite
            any::yulab.utils
            any::ggnewscale
            any::reshape2
            any::ggplotify
            any::glue
            any::ggrepel
            any::magick
            coolbutuseless/devout
            any::devtools
            any::XML
            any::htmltools
            any::plotly
            any::scales
            any::ggridges
            any::ade4
            YuLab-SMU/tidytree
            YuLab-SMU/treeio
            YuLab-SMU/ggtree
            YuLab-SMU/ggtreeExtra@devel

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
